import type { Patient, Doctor } from '../types';

export const INITIAL_DOCTORS: Doctor[] = [
  { id: 'doc-1', name: 'Dr. Sarah Jenkins', specialty: 'General', roomNumber: 'Room 101', status: 'active' },
  { id: 'doc-2', name: 'Dr. Amit Patel', specialty: 'Pediatrics', roomNumber: 'Room 102', status: 'active' },
  { id: 'doc-3', name: 'Dr. Elena Rostova', specialty: 'Cardiology', roomNumber: 'Room 201', status: 'active' },
  { id: 'doc-4', name: 'Dr. Marcus Vance', specialty: 'Orthopedics', roomNumber: 'Room 202', status: 'active' },
  { id: 'doc-5', name: 'Dr. Priya Nair', specialty: 'Dermatology', roomNumber: 'Room 103', status: 'active' },
];

export const generateMockPatients = (): Patient[] => {
  const now = new Date();
  
  const createPastDate = (minutesAgo: number) => {
    return new Date(now.getTime() - minutesAgo * 60 * 1000).toISOString();
  };

  return [
    // Completed patients (for analytics)
    {
      id: 'p-1',
      tokenNumber: 'A101',
      name: 'John Doe',
      age: 45,
      gender: 'Male',
      symptoms: 'Mild chest tightness, routine checkup',
      triageLevel: 'routine',
      department: 'Cardiology',
      assignedDoctorId: 'doc-3',
      status: 'completed',
      createdAt: createPastDate(180),
      calledAt: createPastDate(160),
      completedAt: createPastDate(140),
    },
    {
      id: 'p-2',
      tokenNumber: 'A102',
      name: 'Emily Watson',
      age: 8,
      gender: 'Female',
      symptoms: 'High fever and cough',
      triageLevel: 'urgent',
      department: 'Pediatrics',
      assignedDoctorId: 'doc-2',
      status: 'completed',
      createdAt: createPastDate(150),
      calledAt: createPastDate(120),
      completedAt: createPastDate(95),
    },
    {
      id: 'p-3',
      tokenNumber: 'A103',
      name: 'Michael Chang',
      age: 62,
      gender: 'Male',
      symptoms: 'Severe lower back pain after lifting',
      triageLevel: 'urgent',
      department: 'Orthopedics',
      assignedDoctorId: 'doc-4',
      status: 'completed',
      createdAt: createPastDate(120),
      calledAt: createPastDate(100),
      completedAt: createPastDate(70),
    },
    {
      id: 'p-4',
      tokenNumber: 'A104',
      name: 'Sarah Smith',
      age: 29,
      gender: 'Female',
      symptoms: 'Allergic reaction/rash on arms',
      triageLevel: 'routine',
      department: 'Dermatology',
      assignedDoctorId: 'doc-5',
      status: 'completed',
      createdAt: createPastDate(90),
      calledAt: createPastDate(75),
      completedAt: createPastDate(50),
    },
    {
      id: 'p-5',
      tokenNumber: 'A105',
      name: 'Robert Johnson',
      age: 50,
      gender: 'Male',
      symptoms: 'Acute abdominal pain, nausea',
      triageLevel: 'emergency',
      department: 'General',
      assignedDoctorId: 'doc-1',
      status: 'completed',
      createdAt: createPastDate(80),
      calledAt: createPastDate(78),
      completedAt: createPastDate(45),
    },

    // Active serving patients
    {
      id: 'p-6',
      tokenNumber: 'A106',
      name: 'David Miller',
      age: 33,
      gender: 'Male',
      symptoms: 'Severe asthma exacerbation',
      triageLevel: 'emergency',
      department: 'General',
      assignedDoctorId: 'doc-1',
      status: 'serving',
      createdAt: createPastDate(40),
      calledAt: createPastDate(35),
    },
    {
      id: 'p-7',
      tokenNumber: 'A107',
      name: 'Lisa Anderson',
      age: 5,
      gender: 'Female',
      symptoms: 'Frequent ear pain',
      triageLevel: 'routine',
      department: 'Pediatrics',
      assignedDoctorId: 'doc-2',
      status: 'serving',
      createdAt: createPastDate(30),
      calledAt: createPastDate(20),
    },

    // Called patients (currently walking to room)
    {
      id: 'p-8',
      tokenNumber: 'A108',
      name: 'James Wilson',
      age: 71,
      gender: 'Male',
      symptoms: 'Shortness of breath, heart palpitations',
      triageLevel: 'emergency',
      department: 'Cardiology',
      assignedDoctorId: 'doc-3',
      status: 'called',
      createdAt: createPastDate(15),
      calledAt: createPastDate(2),
    },

    // Waiting patients (by priority: Emergency -> Urgent -> Routine)
    {
      id: 'p-9',
      tokenNumber: 'A109',
      name: 'Sophia Martinez',
      age: 24,
      gender: 'Female',
      symptoms: 'Deep laceration on hand, bleeding controlled',
      triageLevel: 'urgent',
      department: 'General',
      assignedDoctorId: 'doc-1',
      status: 'waiting',
      createdAt: createPastDate(12),
    },
    {
      id: 'p-10',
      tokenNumber: 'A110',
      name: 'William Taylor',
      age: 12,
      gender: 'Male',
      symptoms: 'Suspected wrist fracture from playground fall',
      triageLevel: 'urgent',
      department: 'Orthopedics',
      assignedDoctorId: 'doc-4',
      status: 'waiting',
      createdAt: createPastDate(10),
    },
    {
      id: 'p-11',
      tokenNumber: 'A111',
      name: 'Olivia Brown',
      age: 38,
      gender: 'Female',
      symptoms: 'Chronic eczema flare-up',
      triageLevel: 'routine',
      department: 'Dermatology',
      assignedDoctorId: 'doc-5',
      status: 'waiting',
      createdAt: createPastDate(8),
    },
    {
      id: 'p-12',
      tokenNumber: 'A112',
      name: 'Lucas Garcia',
      age: 3,
      gender: 'Male',
      symptoms: 'Mild diaper rash, feeding advice',
      triageLevel: 'routine',
      department: 'Pediatrics',
      assignedDoctorId: 'doc-2',
      status: 'waiting',
      createdAt: createPastDate(5),
    },
    
    // No-show patients
    {
      id: 'p-13',
      tokenNumber: 'A100',
      name: 'Thomas Anderson',
      age: 31,
      gender: 'Male',
      symptoms: 'Mild sore throat',
      triageLevel: 'routine',
      department: 'General',
      assignedDoctorId: 'doc-1',
      status: 'no-show',
      createdAt: createPastDate(120),
      calledAt: createPastDate(90),
    }
  ];
};
